const fs = require("fs");

// Helper function to get top 10 sorted by a specific key in descending order
function getTop10(data, key) {
  return data.sort((a, b) => b[key] - a[key]).slice(0, 10);
}

function processSeasonData(seasonData) {
  // If seasonData is empty or not an array, return empty results
  if (!Array.isArray(seasonData)) {
    return {};
  }

  // Compute top 10 lists for each category
  const topOrangeCap = getTop10([...seasonData], "runs"); // Top 10 by runs
  const topFours = getTop10([...seasonData], "fours"); // Top 10 by fours
  const topSixes = getTop10([...seasonData], "sixes"); // Top 10 by sixes
  const topCenturies = getTop10([...seasonData], "centuries"); // Top 10 by centuries
  const topFifties = getTop10([...seasonData], "fifties"); // Top 10 by fifties

  return {
    orangeCap: topOrangeCap,
    mostFours: topFours,
    mostSixes: topSixes,
    mostCenturies: topCenturies,
    mostFifties: topFifties,
  };
}

function processAllSeasons(rawData) {
  const processed = {};

  // Iterate over each season in the raw data
  for (const season in rawData) {
    if (rawData.hasOwnProperty(season)) {
      processed[season] = processSeasonData(rawData[season]);
    }
  }

  return processed;
}

(function main() {
  try {
    // Read the raw data file generated by your scraper
    const rawData = JSON.parse(
      fs.readFileSync("last5seasonsData1.json", "utf-8")
    );
    const processedData = processAllSeasons(rawData);

    // Save the processed data to a new JSON file
    fs.writeFileSync(
      "processedData1.json",
      JSON.stringify(processedData, null, 2),
      "utf-8"
    );
    console.log("Processed data saved to processedData.json");
  } catch (error) {
    console.error("Error processing data:", error);
  }
})();
